import { config } from "dotenv";
config()
export const { PORT, FIREBASE_PROJECT_ID, FIREBASE_PRIVATE_KEY, FIREBASE_CLIENT_EMAIL, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET, FRONTEND_URL, JWT_SECRET, RATE_LIMIT_WINDOW_MS, RATE_LIMIT_MAX_REQUESTS } = process.env;
